server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index cardapio.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # cache leve para os assets estáticos
    location ~* \.(css|js)$ {
        expires 1h;
        add_header Cache-Control "public";
    }
}
